### ISSUE TITLE
Best to pass "next" into the inner function?

### ISSUE THREAD

**Issue by johnnysprinkles** [davesag/route-async#15]
I see this code

    Promise.resolve(route(req, res)).catch(next)

and if the route you're wrapping handles errors itself it will break, since "next" is undefined. Handlers may very well do something like:

    let myHandler = async (req, res, next) {
      try {
        let x = await something();
        res.send(x);
      } catch (e) {
        next(e);
      }
    }

I'd suggest just changing your line of code to be:

    Promise.resolve(route(req, res, next)).catch(next)

**Comment by davesag** [comment]
That's true but in general routes are not supposed to use `next`, that's what distinguishes a route from a piece of middleware.

That said I can see advantages in also allowing middleware to be wrapped like this, so I'll look at making this change.

**Comment by davesag** [comment]
actually, thinking about it I am not going to make this change as `next` is always going to be an error handler.  One of the points of wrapping routes like this is to avoid the `try { ... } catch (err) { ... }` clutter in your own routes.

I'll update the docs.
